services:
  ubuntu:
    image: ubuntu:24.04
    ports:
      - "2222:22"
    container_name: ubuntu
    volumes:
      - /This_NAS/Teams/docker/ubuntu:/root
    command: ["/bin/bash", "/root/init.sh"]
    devices:
      - /dev/dri:/dev/dri
    privileged: true
    restart: unless-stopped